services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'klahnen/cfn-lint']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
