name: CFN Lint
description: Runs cfn-lint in a Docker container
author: https://github.com/klahnen
requirements:
  - docker
configuration:
  properties:
    templates:
      type: string
  additionalProperties: false
