name: CFN Lint
description: Runs cfn-lint in a Docker container using .cfnlintrc.yml configuration
author: https://github.com/klahnen
requirements:
  - docker
configuration:
  properties:
    config-file:
      type: string
  additionalProperties: false
